"""First migration

Revision ID: 2e42c17ab6d0
Revises: 
Create Date: 2017-10-02 16:48:52.302976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e42c17ab6d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('email_UNIQUE', table_name='users')
    op.drop_index('id_UNIQUE', table_name='users')
    op.drop_index('username_UNIQUE', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username_UNIQUE', 'users', ['username'], unique=True)
    op.create_index('id_UNIQUE', 'users', ['id'], unique=True)
    op.create_index('email_UNIQUE', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
